# 問題

- FrozenLake8x8-v0
- 8x8 の FrozenLake問題

# アルゴリズム

- Q テーブル
- グリーディー法
- TD-Q学習

# 実行環境

- CPU: Core i7 @2.80GHz
- Mem: 16GB
- HDD: 4TB
- GPU: GeForce1050Ti 4GB
- OS: Ubuntu16.04LTS
- Con: Docker CE/tensorflow1.4.0-gpu/Python3.5.2

In [1]:
import gym
import numpy as np

In [2]:
# 問題：
env = gym.make('FrozenLake8x8-v0')

In [3]:
# Qテーブル初期化
Q = np.zeros([env.observation_space.n, env.action_space.n])
# 学習レート
lr = 0.8
# 割引率
y = 0.95
# 何回試行するか
num_episodes = 2000
# 報酬一覧を格納する配列
rList = []

In [4]:
# num_episodes 回まわす
for i in range(num_episodes):
    # 状態の初期化
    s = env.reset()
    # 報酬の累積和
    rAll = 0
    # Holeに落ちたらdieのd
    d = False
    # 1試行内のカウンタ
    j = 0
    # 
    while j < 99:
        j += 1
        # グリーディー法
        # Q[s,:] あるstateの時のactionごとのQ値を格納する配列
        # np.random.randn(1, env.action_space.n) * ( 1.0 / (i + 1) ) ノイズ
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n) * ( 1.0 / (i + 1) ) ) 
        # アクションの実行結果を取得する
        s1, r, d, _ = env.step(a)
        # ベルマン方程式を更新する、その際学習率をかけてちょっとだけ学習させる
        Q[s,a] = Q[s,a] + lr * (r + y*np.max(Q[s1,:]) - Q[s, a])
        # 報酬の総和：今回の報酬rを足す
        rAll += r
        # 状態を更新
        s = s1
        # Hole に落ちていないなら次のstep()を実行する
        if d == True:
            break
    # 報酬一覧に今回の結果を追加する
    rList.append(rAll)

In [5]:
print("回数ごとの結果:", str( sum(rList)/num_episodes) )

回数ごとの結果: 0.2115


In [6]:
print("最終的なQテーブルの値")
print(Q)

最終的なQテーブルの値
[[  2.24316011e-03   2.22122370e-03   8.49511283e-03   4.19708816e-02]
 [  2.36072542e-03   2.83232870e-03   1.01429819e-02   7.07214898e-02]
 [  2.26259342e-03   9.45827623e-02   2.54240696e-03   5.03313430e-03]
 [  2.21011577e-03   1.78971873e-03   1.72336723e-03   1.01425332e-01]
 [  1.81385818e-03   3.55604606e-03   8.95703973e-02   2.06134151e-03]
 [  2.19418513e-03   1.36951606e-01   0.00000000e+00   2.33265531e-03]
 [  2.34022791e-03   2.24609252e-03   1.64860584e-01   2.23121250e-03]
 [  2.32942532e-03   0.00000000e+00   1.00927593e-01   2.21298926e-03]
 [  1.99064292e-03   2.27958919e-03   4.89755199e-03   4.67242879e-02]
 [  4.76712267e-03   1.82963986e-03   2.32373313e-03   5.50504682e-02]
 [  1.94641970e-03   2.22487620e-03   3.28938681e-03   2.64426965e-02]
 [  1.70494091e-03   7.51202807e-05   3.03685931e-04   8.63202970e-02]
 [  3.04928750e-03   1.72742835e-03   3.35905591e-03   1.09514075e-01]
 [  2.02695177e-03   3.84182883e-03   1.07380555e-01   0.00000000