# Variable

numpy配列から作れる

In [1]:
import chainer
import numpy as np
from chainer import Variable

In [3]:
# numpy配列を作成
input_array = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float32)
print(input_array)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [4]:
# Variable オブジェクトに変換
x = Variable(input_array)
print(x.data)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [9]:
# 計算
#y = x * 2 + 1
y = x ** 2 + 2 * x + 1 #微分系は $$$y' = 2x+2$
print(y.data)

[[  4.   9.  16.]
 [ 25.  36.  49.]]


In [10]:
# 微分値を求める
y.grad = np.ones((2, 3), dtype=np.float32)
# y→xと遡って微分値を求める
y.backward()
# y = x * 2 + 1 の微分系は　y=  2
print(x.grad)

[[  6.   8.  10.]
 [ 12.  14.  16.]]
