# Links

層間の結合をあらわす

In [1]:
import chainer
import numpy as np
from chainer import Variable
import chainer.links as L

In [2]:
# LinksのLinearLink（入力した係数をかけたものと、バイアス全て足し合わせる）関数によりオブジェクト l を作成
l = L.Linear(3, 2)
print(l.W.data)
print(l.b.data)

[[-0.06878837 -0.24217804  0.43447807]
 [-0.7334342  -0.70521271 -0.30952135]]
[ 0.  0.]


In [5]:
# オブジェクトlによりyを計算
#input_array = np.array([[1, 2, 3]], dtype = np.float32)
input_array = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.float32)
x = Variable(input_array)
y = l(x)
print(y.data)

[[ 0.7502898  -3.0724237 ]
 [ 1.12082481 -8.31692886]]


In [6]:
# l の勾配をゼロに初期化
l.cleargrads()

# y →　l と遡って微分の計算
#y.grad = np.ones((1, 2), dtype = np.float32) # 配列１つに要素2つ
y.grad = np.ones((2, 2), dtype = np.float32) # 配列2つに要素2つ
y.backward()
print(l.W.grad)
print(l.b.grad)

[[ 5.  7.  9.]
 [ 5.  7.  9.]]
[ 2.  2.]


# 課題

様々なLinear.Link の型式を試してみましょう。L.Linear(3, 2)の数値を変更してみましょう。

In [7]:
# LinksのLinearLink（入力した係数をかけたものと、バイアス全て足し合わせる）関数によりオブジェクト l を作成
l = L.Linear(4, 2)
print(l.W.data)
print(l.b.data)

[[-0.33575255  0.17525055  0.59400809  0.43941531]
 [ 0.27309164 -0.44317466 -0.63321924 -0.44898087]]
[ 0.  0.]


In [8]:
# オブジェクトlによりyを計算
#input_array = np.array([[1, 2, 3]], dtype = np.float32)
input_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype = np.float32)
x = Variable(input_array)
y = l(x)
print(y.data)

[[ 3.55443406 -4.30883884]
 [ 7.04611969 -9.31797123]]


In [9]:
# l の勾配をゼロに初期化
l.cleargrads()

# y →　l と遡って微分の計算
#y.grad = np.ones((1, 2), dtype = np.float32) # 配列１つに要素2つ
y.grad = np.ones((2, 2), dtype = np.float32) # 配列2つに要素2つ
y.backward()
print(l.W.grad)
print(l.b.grad)

[[  6.   8.  10.  12.]
 [  6.   8.  10.  12.]]
[ 2.  2.]
