# Chain

パラメータの管理、GPUへの移行、データの保存など、様々な面でニュラールネットワークの構築を支援


In [2]:
# coding: UTF-8
import chainer
import numpy as np
from chainer import Variable, Chain
import chainer.links as L

In [4]:
# 関数で記述
l1 = L.Linear(4, 3)
l2 = L.Linear(3, 2)

def my_forward(x):
    h = l1(x)
    return l2(h)

In [6]:
# 動作検証
import_array = np.array([[1, 2, 3, 4]], dtype = np.float32)
x = Variable(import_array)
y = my_forward(x)
print(y.data)

[[-5.36451006 -0.37144101]]


In [8]:
# クラスで記述
class MyClass:
    def __init__(self):
        self.l1 = L.Linear(4, 3)
        self.l2 = L.Linear(3, 2)
    
    def forward(self, x):
        h = self.l1(x)
        return self.l2(h)

In [9]:
# クラスの動作検証
import_array = np.array([[1, 2, 3, 4]], dtype = np.float32)
x = Variable(import_array)
my_class = MyClass()
y = my_class.forward(x)
print(y.data)

[[-1.6603806   4.91491795]]


In [10]:
# Chainクラスを継承
class MyChain(Chain):
    def __init__(self):
        self.l1 = L.Linear(4, 3)
        self.l2 = L.Linear(3, 2)
    
    def __call__(self, x):
        h = self.l1(x)
        return self.l2(h)

In [11]:
# Chainクラスの動作検証
import_array = np.array([[1, 2, 3, 4]], dtype = np.float32)
x = Variable(import_array)
my_chain = MyChain()
y = my_chain(x)
print(y.data)

[[-1.90520024 -0.93567324]]
