# ディープラーニングによる分類

## Iris データセット

あやめの品種分類
0: Setosa, 1: Veriscicolor, 2: Versinica

各花ごとに、4つの測定値
- Sepal length
- Sepal width
- Petal length
- Petal width

## ディープラーニングによる品種分類

各花ごとに、4つの測定値＋品種のデータ
→全部で150組

最低限の実装によるディープラーニング
→ 入力層には4つ、出力層には3つのニューロン
→ 4層からなるニューラルネットワークを訓練
→ 訓練済みのニューラルネットワークによる品種分類

## ニューラルネットワーク

- 入力層
 - Sepal length
 - Sepal width
 - Petal length
 - Petal width
 
- 隠れ層2層
 - ニューロン数6
 - ニューロン数6

- 出力層
 - Setosa
 - Versicolor
 - Versinica

### 訓練

出力と正解値の誤差を伝播させ、ニューラルネットワークを訓練

### 予測

出力の値が最も大きいものに品種を分類

データセットを訓練用データとテストデータに分ける

In [1]:
# coding: UTF-8

import chainer
from chainer import Variable, Chain, optimizers
import chainer.links as L
import chainer.functions as F

import numpy as np
from sklearn import datasets # Scikit Learn にIris dataset が含まれている

In [2]:
# Iris データの読み込み
iris_data = datasets.load_iris()
print(iris_data)

{'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
 

In [3]:
x = iris_data.data.astype(np.float32)
t = iris_data.target
n = t.size

print(x)
print(t)
print(n)

[[ 5.0999999   3.5         1.39999998  0.2       ]
 [ 4.9000001   3.          1.39999998  0.2       ]
 [ 4.69999981  3.20000005  1.29999995  0.2       ]
 [ 4.5999999   3.0999999   1.5         0.2       ]
 [ 5.          3.5999999   1.39999998  0.2       ]
 [ 5.4000001   3.9000001   1.70000005  0.40000001]
 [ 4.5999999   3.4000001   1.39999998  0.30000001]
 [ 5.          3.4000001   1.5         0.2       ]
 [ 4.4000001   2.9000001   1.39999998  0.2       ]
 [ 4.9000001   3.0999999   1.5         0.1       ]
 [ 5.4000001   3.70000005  1.5         0.2       ]
 [ 4.80000019  3.4000001   1.60000002  0.2       ]
 [ 4.80000019  3.          1.39999998  0.1       ]
 [ 4.30000019  3.          1.10000002  0.1       ]
 [ 5.80000019  4.          1.20000005  0.2       ]
 [ 5.69999981  4.4000001   1.5         0.40000001]
 [ 5.4000001   3.9000001   1.29999995  0.40000001]
 [ 5.0999999   3.5         1.39999998  0.30000001]
 [ 5.69999981  3.79999995  1.70000005  0.30000001]
 [ 5.0999999   3.79999995  1.5 